Repository pysat/pysat, pull requests merged in 2019-07, with the labels that each got.

#231 Orbit iteration fix when no loaded data (non-mlt orbits)
  pysat/_orbits.py
  pysat/tests/test_orbits.py
Labels: bug

#245 Ap to kp
  pysat/instruments/methods/sw.py
  pysat/instruments/sw_kp.py
  pysat/tests/test_sw.py
Labels: enhancement

#232 TIEGCM comparison additions
  pysat/instruments/ucar_tiegcm.py
  pysat/model_utils.py
Labels: bug, enhancement

#249 Limit pandas to < 0.25
  setup.py
Labels: bug
