Repository pysat/pysat, pull requests merged in 2019-04, with the labels that each got.

#210 pyflakes cleanup
  pysat/_files.py
  pysat/_instrument.py
  pysat/_orbits.py
  pysat/instruments/cosmic_gps.py
  pysat/model_utils.py
  pysat/tests/test_ftp_instruments.py
  pysat/tests/test_icon_ivm.py
  pysat/tests/test_instruments.py
  pysat/tests/test_omni_hro.py
  pysat/tests/test_orbits.py
  pysat/tests/test_ssnl_ave.py
  pysat/tests/test_ssnl_occur_prob.py
  pysat/tests/test_ssnl_plot.py
  pysat/tests/test_utils.py
  pysat/tests/test_utils_stats.py
  pysat/tests/test_utils_time.py
  pysat/utils/time.py
Labels: style

#211 prelim download bugfix
  pysat/instruments/sw_f107.py
Labels: bug

#209 Python 3.7 testing and compatibility
  .travis.yml
  pysat/_instrument.py
  pysat/_orbits.py
Labels: bug, testing

#212 Update sw_f107.py
  pysat/instruments/sw_f107.py
Labels: bug

#213 update f107 url
  pysat/instruments/sw_f107.py
Labels: bug

#215 Version limits for numpy and scipy
  setup.py
Labels: bug
