Repository pysat/pysat, pull requests merged in 2019-02, with the labels that each got.

#139 SW merging
  pysat/instruments/__init__.py
  pysat/instruments/sw_f107.py
  pysat/instruments/sw_kp.py
  pysat/instruments/sw_methods.py
  pysat/model_utils.py
  pysat/tests/test_instruments.py
  pysat/tests/test_sw.py
  pysat/tests/test_utils.py
  pysat/utils.py
Labels: enhancement

#145 Added OCB testing option
  pysat/instruments/pysat_testing.py
Labels: testing

#143 cdaweb access through requests
  pysat/instruments/__init__.py
  pysat/instruments/jro_isr.py
  pysat/instruments/nasa_cdaweb_methods.py
  pysat/instruments/omni_hro.py
  pysat/instruments/supermag_magnetometer.py
  pysat/instruments/sw_dst.py
  pysat/tests/test_ftp_instruments.py
  pysat/tests/test_instruments.py
  pysat/tests/test_sw.py
Labels: enhancement

#162 Metadata update
  pysat/model_utils.py
Labels: bug

#166 Update download procedure for prelim F10.7 data
  pysat/instruments/sw_f107.py
Labels: bug

#168 Update of cosmic downloads with requests
  pysat/instruments/cosmic2013_gps.py
  pysat/instruments/cosmic_gps.py
  pysat/instruments/nasa_cdaweb_methods.py
Labels: bug, enhancement

#176 Updates to pysat testing instruments
  pysat/instruments/pysat_testadd1.py
  pysat/instruments/pysat_testadd2.py
  pysat/instruments/pysat_testadd3.py
  pysat/instruments/pysat_testadd4.py
  pysat/instruments/pysat_testing.py
  pysat/instruments/pysat_testing2d.py
  pysat/instruments/pysat_testing2d_xarray.py
  pysat/instruments/pysat_testing_xarray.py
  pysat/instruments/pysat_testsmall.py
  pysat/instruments/pysat_testsmall2.py
Labels: bug, testing
