Repository pysat/pysat, pull requests merged in 2019-10, with the labels that each got.

#289 ENH: C/NOFS IVM Cleaning Routine Update
  CHANGELOG.md
  pysat/instruments/cnofs_ivm.py
Labels: enhancement

#307 BUG: Travis update - generalize environment for forks
  .travis.yml
  CHANGELOG.md
  pysat/__init__.py
Labels: bug

#305 S4 scintillation added to cosmic_gps
  CHANGELOG.md
  pysat/instruments/cosmic_gps.py
Labels: enhancement

#317 BUG: IVM clean fix
  CHANGELOG.md
  pysat/instruments/cnofs_ivm.py
  pysat/instruments/demeter_iap.py
  pysat/model_utils.py
Labels: bug, enhancement, instruments

#313 BUG: COSMIC downloads
  CHANGELOG.md
  pysat/instruments/cosmic_gps.py
Labels: bug
