Repository pysat/pysat, pull requests merged in 2019-03, with the labels that each got.

#164 Utils restructure
  pysat/_files.py
  pysat/_instrument.py
  pysat/instruments/madrigal_methods.py
  pysat/instruments/omni_hro.py
  pysat/instruments/sw_f107.py
  pysat/instruments/sw_kp.py
  pysat/instruments/sw_methods.py
  pysat/tests/test_files.py
  pysat/tests/test_instrument.py
  pysat/tests/test_utils.py
  pysat/tests/test_utils_coords.py
  pysat/tests/test_utils_stats.py
  pysat/tests/test_utils_time.py
  pysat/utils.py
  pysat/utils/__init__.py
  pysat/utils/_core.py
  pysat/utils/coords.py
  pysat/utils/stats.py
  pysat/utils/time.py
Labels: enhancement

#178 Check for bad datetime when loading data
  pysat/_instrument.py
Labels: bug

#179 Import reload
  pysat/tests/test_files.py
  pysat/tests/test_instrument.py
  pysat/tests/test_instruments.py
  pysat/tests/test_ssnl_ave.py
  pysat/tests/test_utils.py
  setup.py
Labels: style, testing

#175 Documentation update
  demo/cnofs_vefi_dc_b_orbit_plots.py
  demo/cosmic_and_ivm_demo.py
  demo/ssnl_occurrence_by_orbit.py
  docs/examples.rst
  docs/images/orbit_00000.png
  docs/images/ssnl_median_ivm_cosmic_1d.png
  docs/images/ssnl_median_ivm_cosmic_2d.png
  docs/images/ssnl_occurrence_by_orbit_demo.png
  docs/new_instrument.rst
  docs/tutorial.rst
Labels: documentation

#173 Future Warning
  pysat/_files.py
  pysat/instruments/omni_hro.py
  pysat/instruments/sw_f107.py
  pysat/instruments/sw_kp.py
  pysat/instruments/sw_methods.py
Labels: FutureWarning

#188 Testing for occur_prob.py
  pysat/ssnl/occur_prob.py
  pysat/tests/test_ssnl_occur_prob.py
Labels: testing

#185 Dmsp clean bugfix
  pysat/instruments/demeter_iap.py
  pysat/instruments/dmsp_ivm.py
Labels: bug

#190 instrument templates update
  .coveragerc
  pysat/instruments/templates/madrigal_pandas.py
  pysat/instruments/templates/netcdf_pandas.py
  pysat/instruments/templates/template_cdaweb_instrument.py
  pysat/instruments/templates/template_instrument.py
Labels: testing

#197 Adds new default directory at home level
  .travis.yml
  pysat/__init__.py
  pysat/tests/test_ftp_instruments.py
  pysat/tests/test_instruments.py
  pysat/tests/test_utils.py
Labels: enhancement

#199 xarray len deprecation fix
  pysat/_custom.py
  pysat/_instrument.py
Labels: FutureWarning

#201 version limits
  setup.py
Labels: testing

#192 More testing
  .travis.yml
  demo/ssnl_occurrence_by_orbit.py
  docs/examples.rst
  pysat/_files.py
  pysat/_instrument.py
  pysat/_meta.py
  pysat/instruments/cosmic2013_gps.py
  pysat/instruments/cosmic_gps.py
  pysat/instruments/sw_kp.py
  pysat/ssnl/plot.py
  pysat/tests/test_constellation.py
  pysat/tests/test_custom.py
  pysat/tests/test_files.py
  pysat/tests/test_ftp_instruments.py
  pysat/tests/test_icon_ivm.py
  pysat/tests/test_instrument.py
  pysat/tests/test_instruments.py
  pysat/tests/test_meta.py
  pysat/tests/test_omni_hro.py
  pysat/tests/test_orbits.py
  pysat/tests/test_ssnl_ave.py
  pysat/tests/test_ssnl_occur_prob.py
  pysat/tests/test_ssnl_plot.py
  pysat/tests/test_sw.py
  pysat/tests/test_utils.py
  pysat/tests/test_utils_coords.py
  pysat/tests/test_utils_stats.py
  pysat/tests/test_utils_time.py
  pysat/utils/_core.py
  pysat/utils/stats.py
Labels: bug, testing
