Repository pysat/pysat, pull requests merged in 2021-06, with the labels that each got.

#812 Load kwarg tests
  pysat/_instrument.py
  pysat/tests/test_instrument.py
Labels: bug, testing

#818 BUG: restore coveralls
  .github/workflows/main.yml
Labels: bug

#822 Doc formatting updates
  CHANGELOG.md
  README.md
  docs/analysis/pysatMissions.rst
  docs/analysis/pysatModels.rst
  docs/analysis/pysatSeasons.rst
  docs/analysis/pysatSpaceWeather.rst
  docs/api.rst
  docs/citing.rst
  docs/conf.py
  docs/dependency.rst
  docs/faq.rst
  docs/images/logo.png
  docs/installation.rst
  docs/instruments/pysatCDAAC.rst
  docs/instruments/pysatIncubator.rst
  docs/instruments/pysatMadrigal.rst
  docs/instruments/pysatMissions.rst
  docs/instruments/pysatModels.rst
  docs/instruments/pysatNASA.rst
  docs/instruments/pysatSpaceWeather.rst
  docs/instruments/testing_instruments.rst
  docs/introduction.rst
  docs/new_instrument.rst
  docs/quickstart.rst
  docs/release_notes.rst
  docs/tutorial/tutorial_analysis.rst
  docs/tutorial/tutorial_basics.rst
  docs/tutorial/tutorial_custom.rst
  docs/tutorial/tutorial_iteration.rst
  docs/tutorial/tutorial_load.rst
  docs/tutorial/tutorial_orbit.rst
  docs/tutorial/tutorial_parameters.rst
  docs/tutorial/tutorial_v3_upgrade.rst
  docs/tutorial/tutorial_verbosity.rst
  pysat/utils/_core.py
  pysat/utils/time.py
  setup.cfg
Labels: documentation

#825 Added `empty_partial` property to the Constellation class
  CHANGELOG.md
  pysat/_constellation.py
  pysat/tests/test_constellation.py
Labels: enhancement
