Repository pysat/pysat, pull requests merged in 2021-10, with the labels that each got.

#915 STY: move `tests.instrument_test_class` to `tests.classes.cls_instrument_library`
  CHANGELOG.md
  docs/dependency.rst
  pysat/tests/classes/cls_instrument_library.py
  pysat/tests/instrument_test_class.py
  pysat/tests/test_instruments.py
Labels: style

#917 BUG: warn users when instantiated via `inst_module` AND `platform`/`name`
  CHANGELOG.md
  pysat/_instrument.py
  pysat/tests/classes/cls_instrument_property.py
Labels: bug

#916 STY: move remaining test class files to `tests.classes`
  pysat/tests/classes/cls_ci.py
  pysat/tests/classes/cls_registration.py
  pysat/tests/test_constellation.py
  pysat/tests/test_files.py
  pysat/tests/test_params.py
  pysat/tests/test_registry.py
  pysat/tests/test_utils.py
  pysat/tests/test_utils_files.py
Labels: style

#919 TST: add the ability to pass kwargs through standard load tests
  CHANGELOG.md
  docs/dependency.rst
  pysat/instruments/pysat_testing.py
  pysat/tests/classes/cls_instrument_library.py
  pysat/utils/_core.py
  setup.cfg
Labels: enhancement, testing

#951 Updated Instrument rename method
  CHANGELOG.md
  docs/instruments/pysatMadrigal.rst
  docs/tutorial/tutorial_basics.rst
  pysat/_instrument.py
  pysat/_meta.py
  pysat/tests/classes/cls_instrument_access.py
  pysat/tests/test_meta.py
  pysat/tests/test_utils.py
  pysat/utils/__init__.py
  pysat/utils/_core.py
Labels: bug, enhancement
