Repository pysat/pysat, pull requests merged in 2021-05, with the labels that each got.

#783 BUG: Data slicing when data does not exist
  CHANGELOG.md
  pysat/_instrument.py
Labels: bug

#797 MAINT: pysatSpaceWeather compatibility
  CHANGELOG.md
  pysat/tests/test_utils_files.py
Labels: bug, testing

#785 Added useful Constellation attributes
  CHANGELOG.md
  pysat/__init__.py
  pysat/_constellation.py
  pysat/_instrument.py
  pysat/_params.py
  pysat/constellations/testing.py
  pysat/tests/test_constellation.py
  pysat/tests/test_instrument.py
  pysat/tests/test_utils_time.py
  pysat/utils/time.py
Labels: enhancement
