Repository pysat/pysat, pull requests merged in 2023-03, with the labels that each got.

#1071 BUG: xarray coords
  CHANGELOG.md
  docs/citing.rst
  docs/tutorial/tutorial_basics.rst
  pysat/_instrument.py
  pysat/tests/classes/cls_instrument_access.py
  pysat/tests/test_instrument.py
Labels: bug

#1075 Added Constellation method `to_inst`
  CHANGELOG.md
  docs/tutorial/tutorial_constellation.rst
  pysat/_constellation.py
  pysat/_instrument.py
  pysat/tests/test_constellation.py
  pysat/tests/test_utils_coords.py
  pysat/utils/coords.py
Labels: enhancement

#1079 BUG: listing files with a yearly cadence
  CHANGELOG.md
  docs/api.rst
  docs/new_instrument.rst
  docs/tutorial/tutorial_custom.rst
  docs/tutorial/tutorial_iteration.rst
  docs/tutorial/tutorial_verbosity.rst
  pysat/_constellation.py
  pysat/_instrument.py
  pysat/instruments/methods/general.py
  pysat/instruments/templates/template_instrument.py
  pysat/tests/classes/cls_instrument_access.py
  pysat/tests/classes/cls_instrument_integration.py
  pysat/tests/classes/cls_instrument_iteration.py
  pysat/tests/classes/cls_instrument_property.py
  pysat/tests/test_files.py
  pysat/tests/test_instrument.py
  pysat/tests/test_utils_io.py
  pysat/utils/io.py
  pysat/utils/testing.py
Labels: bug, testing

#1086 BUG: empty evaluation doesn't work with xarray
  CHANGELOG.md
  pysat/_instrument.py
  pysat/tests/test_instrument.py
  pysat/utils/_core.py
Labels: bug

#1087 Constellation example
  CHANGELOG.md
  docs/tutorial/tutorial_constellation.rst
Labels: documentation

#1089 DOC: Updated project standards docs
  CHANGELOG.md
  CONTRIBUTING.md
  docs/devel/pysatEcosystem_Template.rst
  docs/devel/pysatTutorials.rst
  docs/ecosystem.rst
  docs/examples.rst
Labels: documentation
